server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microservicio-mantenimiento
            uri: lb://microservicio-mantenimiento
            predicates:
                - Path=/mantenimiento/**
          - id: microservicio-admin
            uri: lb://microservicio-admin
            predicates:
              - Path=/administrar/**
          - id: microservicio-monopatin
            uri: lb://microservicio-monopatin
            predicates:
              - Path=/monopatines/**
          - id: microservicioparada
            uri: lb://microservicioparada
            predicates:
              - Path=/paradas/**
          - id: microservicio-user
            uri: lb://microservicio-user
            predicates:
              - Path=/users/**
          - id: microservicio-viaje
            uri: lb://microservicio-viaje
            predicates:
              - Path=/viajes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

