server:
  port: ${PORT:${SERVER_PORT:0}}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
application-description: Mantenimiento API
application-version: 1.0
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: microservicio-mantenimiento
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/mantenimiento
  jpa:
    enabled: false  # Disable JPA
  datasource:
    enabled: false  # Disable datasource configuration


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      zone: default
