server:
  port: ${PORT:${SERVER_PORT:0}}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
application-description: Monopatin API
application-version: 1.0
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: microservicio-monopatin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3303/monopatines?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      zone: default